import type { Metadata } from "next";
import { Inter, Roboto, Poppins, Montserrat } from "next/font/google"
import "./globals.css";
import { NuqsAdapter } from "nuqs/adapters/next/app";


const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
})

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700"], // required
  variable: "--font-roboto",
})

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600"],
  variable: "--font-poppins",
})

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
})



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`
          ${inter.className}
          ${inter.variable}
          ${roboto.variable}
          ${poppins.variable}
          ${montserrat.variable}
          antialiased
        `}
      >
        <NuqsAdapter>
          {children}
        </NuqsAdapter>
      </body>
    </html>
  );
}


